import fs from "node:fs";
import process from "node:process";

function main(args: string[]): void {
    if (args.length !== 1) {
        console.log("Usage: generate_ast <output directory>");
        return process.exit(64);
    }

    const outputDir = args[0];

    defineAst(outputDir, "Expr", [
        "Binary   + left: Expr, operator: Token, right: Expr",
        "Grouping + expression: Expr",
        "Literal  + value: object",
        "Unary    + operator: Token, right: Expr",
    ]);
}

function defineAst(outputDir: string, baseName: string, types: string[]): void {
    const path = `${outputDir}/${baseName}.ts`;
    let fileContent = `// Auto-generated by Lox. Do not edit.\n`;
    fileContent += `\n`;
    fileContent += `import { Token } from "tokens/token";`;
    fileContent += `\n`;

    fileContent += `\n`;
    fileContent += `export interface Visitor<R> {\n`;
    types.forEach((type) => {
        const className = type.split("+")[0].trim();
        fileContent += `  visit${className}${baseName}(${baseName.toLowerCase()}: ${className}): R;\n`;
    });
    fileContent += `}\n`;
    fileContent += `\n`;

    fileContent += `export abstract class ${baseName} {\n`;
    fileContent += `  abstract accept<R>(visitor: Visitor<R>): R;\n`;
    fileContent += `}\n`;
    fileContent += `\n`;

    types.forEach((type) => {
        const className = type.split("+")[0].trim();
        const fields = type.split("+")[1].trim();
        fileContent += defineType(baseName, className, fields);
        fileContent += `\n`;
    });

    fs.writeFileSync(path, fileContent, { encoding: "utf-8" });
    console.log(`Successfully generated AST for ${baseName} at ${path}`);
}

function defineType(baseName: string, className: string, fieldList: string): string {
    const fields = fieldList.split(", ");
    const constructorParams = fields.map((field) => `public readonly ${field}`).join(", ");
    const visitorMethod = `  accept<R>(visitor: Visitor<R>): R {
    return visitor.visit${className}${baseName}(this);
  }`;

    return `export class ${className} extends ${baseName} {
  constructor(${constructorParams}) {
    super();
  }

${visitorMethod}
}`;
}

main(["/Users/perepalacin/Documents/pere-repos/crafting-compilers/typescript/src/expression"]);
