// Auto-generated by Lox. Do not edit.

import { Expr } from "@/expression/expr";

export interface Visitor<R> {
    visitExpressionStmt(stmt: StmtExpression): R;
    visitPrintStmt(stmt: StmtPrint): R;
}

export abstract class Stmt {
    abstract accept<R>(visitor: Visitor<R>): R;
}

export class StmtExpression extends Stmt {
    constructor(public readonly expression: Expr) {
        super();
    }

    accept<R>(visitor: Visitor<R>): R {
        return visitor.visitExpressionStmt(this);
    }
}

export class StmtPrint extends Stmt {
    constructor(public readonly expression: Expr) {
        super();
    }

    accept<R>(visitor: Visitor<R>): R {
        return visitor.visitPrintStmt(this);
    }
}
